##Exercise 1

A. Create an ndarry object (A) with any values from 1 to 100 in a nested Python List. You can choose your range from the given values (1-100).

Given that A is an ndarray object, many functionalities in numpy could be accessed by:
Make sure to explain each line of codes that you have created.
Using a property of the ndarray object
e.g. A.shape
Using a method of the ndarray object
e.g. A.max()
Using a numpy function and passing an ndarray
e.g. np.max(A).

In [1]:
import numpy as np

A = np.array([[i for i in range(1, 11)] for _ in range(10)])

print("A:\n", A)

print("Shape of A:", A.shape)

A:
 [[ 1  2  3  4  5  6  7  8  9 10]
 [ 1  2  3  4  5  6  7  8  9 10]
 [ 1  2  3  4  5  6  7  8  9 10]
 [ 1  2  3  4  5  6  7  8  9 10]
 [ 1  2  3  4  5  6  7  8  9 10]
 [ 1  2  3  4  5  6  7  8  9 10]
 [ 1  2  3  4  5  6  7  8  9 10]
 [ 1  2  3  4  5  6  7  8  9 10]
 [ 1  2  3  4  5  6  7  8  9 10]
 [ 1  2  3  4  5  6  7  8  9 10]]
Shape of A: (10, 10)


B.Create a 5x5 integer-array filled with ones.

Check its shape, size, and number of dimensions. Explain briefly the codes you have created by writing a comment beside the code.

In [2]:
B = np.ones((5, 5), dtype=int)

print("B:\n", B)

print("Shape of B:", B.shape)
print("Size of B:", B.size)
print("Dimensions of B:", B.ndim)

B:
 [[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]
Shape of B: (5, 5)
Size of B: 25
Dimensions of B: 2


C. Create an array of values from -5 to + 5. Multiply each value with 2. Print the resulting array.

In [3]:
C = np.arange(-5, 6)

C *= 2

print("C:", C)

C: [-10  -8  -6  -4  -2   0   2   4   6   8  10]


##Exercise 2

A. Choose the values from the range of numbers 1 to 100.

1.Create an array with 30 values within the range of numbers given. You can choose your own start value and stop value. However, the incrementing value will be 2.

In [4]:
import numpy as np

arr = np.arange(10, 69, 2)

print("Array:", arr)

Array: [10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48 50 52 54 56
 58 60 62 64 66 68]


2.Multiply the resulting array with 3. Print the result.

In [5]:
arr *= 3

print("Modified Array:", arr)

Modified Array: [ 30  36  42  48  54  60  66  72  78  84  90  96 102 108 114 120 126 132
 138 144 150 156 162 168 174 180 186 192 198 204]


##Exercise 3

A. Create a four-dimensional array of random integers in the interval [0, 12]. Print the result.
1. Get the dimensions, shape, and size.
    * Explain what is the result briefly by writing a comment before the code.

In [6]:
import numpy as np

four_dim_array = np.random.randint(0, 13, size=(2, 3, 4, 5))

print("Four-dimensional Array:\n", four_dim_array)

Four-dimensional Array:
 [[[[ 0  3  3  6 12]
   [ 8  1 11  5  9]
   [ 9 10  6  4  8]
   [12  9 11  6  9]]

  [[ 9  5  9  2  8]
   [ 1 11  2  0  1]
   [10  8  1  3 11]
   [12  0  8  2  1]]

  [[ 7  7  5  4  8]
   [ 4 12  4 11  2]
   [ 0  2  7  9  8]
   [ 0 11  7 10  5]]]


 [[[11  5  8 11  7]
   [ 1  7  2  3  5]
   [ 3  0 12  6  0]
   [ 8  9  0 10  5]]

  [[12 10  1  0  8]
   [ 5  6 10  3 10]
   [12  4  5  8  1]
   [ 3  5 11 12 12]]

  [[ 5  6  1  7  1]
   [ 7  1  1  3  5]
   [ 7  6 12  4  0]
   [ 0  0  6 12  6]]]]


B. Get the maximum number for each dimensions and display it.
   * Explain what is the result briefly by writing a comment before the code.


In [9]:
max_values = four_dim_array.max(axis=(0, 1, 2, 3))

print("Maximum number for each dimension:", max_values)

Maximum number for each dimension: 48


C. Multipy each array with 4. What is its result?
    * Write a brief explanation on the multiplication process.


In [8]:
four_dim_array *= 4

print("Array after multiplication:\n", four_dim_array)

Array after multiplication:
 [[[[ 0 12 12 24 48]
   [32  4 44 20 36]
   [36 40 24 16 32]
   [48 36 44 24 36]]

  [[36 20 36  8 32]
   [ 4 44  8  0  4]
   [40 32  4 12 44]
   [48  0 32  8  4]]

  [[28 28 20 16 32]
   [16 48 16 44  8]
   [ 0  8 28 36 32]
   [ 0 44 28 40 20]]]


 [[[44 20 32 44 28]
   [ 4 28  8 12 20]
   [12  0 48 24  0]
   [32 36  0 40 20]]

  [[48 40  4  0 32]
   [20 24 40 12 40]
   [48 16 20 32  4]
   [12 20 44 48 48]]

  [[20 24  4 28  4]
   [28  4  4 12 20]
   [28 24 48 16  0]
   [ 0  0 24 48 24]]]]
